DROP TABLE IF EXISTS EMP_MASTER;
CREATE TABLE  EMP_MASTER (
  EMP_ID int(10) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME varchar(64) NOT NULL,
  LAST_NAME varchar(64) NOT NULL,
  EMAIL VARCHAR(64), 
  BIRTH_DATE DATE, 
  YEAR_OF_EXP INTEGER);